Login and registration tests
szymonpoltorak/Library pull request #28
Opened 2023-12-05 15:45 UTC by JakubNiewadzi

2023-12-05 16:16 UTC, szymonpoltorak requested changes

2023-12-05 16:16 UTC, szymonpoltorak commented on cinema-backend/src/test/java/pl/edu/pw/ee/cinemabackend/runners/LoginPageSeleniumTests.java
> +        //TODO assert cinema home page url
Pozostawione `TODO`

2023-12-05 16:16 UTC, szymonpoltorak commented on cinema-backend/src/test/java/pl/edu/pw/ee/cinemabackend/runners/LoginPageSeleniumTests.java
> +    void setup() {
methods should be `final`

2023-12-05 16:16 UTC, szymonpoltorak commented on cinema-backend/src/main/java/pl/edu/pw/ee/cinemabackend/pages/RegisterPage.java
> +    public void clickReturn(){
why not final

2023-12-05 20:25 UTC, szymonpoltorak requested changes

2023-12-05 20:25 UTC, szymonpoltorak commented on cinema-backend/src/test/java/pl/edu/pw/ee/cinemabackend/runners/RegisterPageSeleniumTests.java
> +    private  WebDriverConfig webDriverConfig;
lul

2023-12-05 20:25 UTC, szymonpoltorak commented on cinema-backend/src/test/java/pl/edu/pw/ee/cinemabackend/runners/RegisterPageSeleniumTests.java
>      @Value("${browser}")
Dodaj jeszcze to co mówiliśmy żeby już było i będzie git

2023-12-06 08:50 UTC, JakubNiewadzi commented on cinema-backend/src/test/java/pl/edu/pw/ee/cinemabackend/runners/RegisterPageSeleniumTests.java
> +    private  WebDriverConfig webDriverConfig;
XD

2023-12-07 06:54 UTC, szymonpoltorak approved these changes

2023-12-07 06:54 UTC, merged